export const HOME_API_CALL_BEGIN = 'HOME_API_CALL_BEGIN';
export const HOME_API_CALL_SUCCESS = 'HOME_API_CALL_SUCCESS';
export const HOME_API_CALL_FAILURE = 'HOME_API_CALL_FAILURE';
export const HOME_API_CALL_DISMISS_ERROR = 'HOME_API_CALL_DISMISS_ERROR';
export const HOME_SET_PRODUCT_IN_FOCUS = 'HOME_SET_PRODUCT_IN_FOCUS';
export const HOME_SET_CART_ITEM = 'HOME_SET_CART_ITEM';
