export const HOME_API_CALL_BEGIN = 'HOME_API_CALL_BEGIN';
export const HOME_API_CALL_SUCCESS = 'HOME_API_CALL_SUCCESS';
export const HOME_API_CALL_FAILURE = 'HOME_API_CALL_FAILURE';
export const HOME_API_CALL_DISMISS_ERROR = 'HOME_API_CALL_DISMISS_ERROR';
export const HOME_STORE_BLOGS = 'HOME_STORE_BLOGS';
export const HOME_SET_BLOG_IN_FOCUS = 'HOME_SET_BLOG_IN_FOCUS';
export const HOME_SET_GALLERY = 'HOME_SET_GALLERY';
